#theme = "modern"
icons = "awesome5"
[theme]
name = "modern"
#[theme.overrides]
#separator = "\ue0b2" 
#[icons]
#name = "awesome5"
#[icons.overrides]
#backlight_empty = "\uf042"
#backlight_full = "\uf042"
#backlight_1 = "\uf042"
#backlight_2 = "\uf042"
#backlight_3 = "\uf042"
#backlight_4 = "\uf042"
#backlight_5 = "\uf042"
#backlight_6 = "\uf042"
#backlight_7 = "\uf042"
#backlight_8 = "\uf042"
#backlight_9 = "\uf042"
#backlight_10 = "\uf042"
#backlight_11 = "\uf042"
#backlight_12 = "\uf042"
#backlight_13 = "\uf042"

#[[block]]
#block = "networkmanager"
#device_format = "{icon}"
#ap_format = "{strenght} {freq}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/var"
alias = "/var"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "custom"
command = 'echo "" $(acpi -i | grep  -o "[0-9]*%" | head -1)'

#command = "acpi -i | grep  -o '[0-9]*%' | head -1"
#[[block]]
#block = "hueshift"
#hue_shifter = "redshift"
#step = 50
#click_temp = 3000

[[block]]
block = "backlight"
minimum = 0
cycle = [0, 25, 50, 75, 100]

[[block]]
block = "sound"

[[block]]
block = "sound"
device_kind="source"
on_click="pactl set-source-volume @DEFAULT_SOURCE@ 25%"

[[block]]
block = "time"
interval = 1
format = "%a %d.%m.%Y %T"

